### ISSUE TITLE
Cursor position jump

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#111]
Opening Neogit makes the cursor jump to the first section after some time. IMO we either have to position the cursor correctly instantly or just not reposition the cursor when it is above the `Head: ....` section

**Comment by RianFuro** [comment]
Ah that's likely on me. The refresh attempts to restore the cursor position after it's finished. Since there's no section to return to on the initial refresh, it goes back to line 1. I initially thought it would be fine in most cases to adjust the cursor position, but I guess we should only explicitly do it after certain operations.
