### ISSUE TITLE
 ✗ Failed to install TimUntersberger/neogit

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [TimUntersberger/neogit#147]

**Comment by TimUntersberger** [comment]
If you are using packer.nvim try to call the command again. This happenend for me yesterday for other plugins aswell, but rerunning the command fixed it.

**Comment by clason** [comment]
For the record, such problems can happen when you force push to master and the local git fails to `git pull` because it cannot fast-forward. You either need to manually `git pull --rebase` or -- if this also fails -- remove and reinstall neogit. (Rewriting history on master is usually not a good idea and should be avoided ;))
