### ISSUE TITLE
Unable to :Neogit & :q or :bd w/o error

### ISSUE THREAD

**Issue by jc00ke** [TimUntersberger/neogit#190]
When I `:Neogit`
![image](https://user-images.githubusercontent.com/18191/130277341-7ba41d26-991b-4a2b-af8d-8b6b07db0043.png)

After running `:Neogit` the current buffer is cloned in a new tab. When I then `:bd` or `:q` I see
![image](https://user-images.githubusercontent.com/18191/130277523-5c2bc870-5a1d-48b2-85c0-58dfe135aa3f.png)

`NVIM v0.6.0-dev+155-g15b736d6e` on Neogit 3b5fa08

**Comment by jc00ke** [comment]
Hmm, I have suspicions that this is related to an update from another library...

**Comment by sindrets** [comment]
@jc00ke this seems to be related to my recent update in diffview. Do you have diffview installed? If so, diffview and neogit will be incompatible until #188 is merged. 

But still, this error is strange. It seems like you only partially updated diffview. Because these errors indicate that you have the updated autocommands, but not the updated lua code. I would try to reinstall diffview if I were you, because the update should not cause these types of errors regardless. It should only mean that you can't open diffview from neogit until my PR is merged.

**Comment by jc00ke** [comment]
Thanks @sindrets! I tried reinstalling diffview and it did not work. NBD, I'll disable it for now and I'll watch #188.

**Comment by TimUntersberger** [comment]
Just merged #188.
