### ISSUE TITLE
Notifications block window operations

### ISSUE THREAD

**Issue by mystilleef** [TimUntersberger/neogit#208]
`Neogit` windows won't close when notifications are present.

Is it possible to provide an option to reduce the timeout of successful notifications? 

It makes sense for error notifications to have longer timeouts.

**Comment by akinsho** [comment]
Not sure if this is related to this issue but I've been seeing a `E5601: Cannot close window, only floating window would remain` when using neogit in a tab whilst also using [`nvim-notify`](https://github.com/rcarriga/nvim-notify). I believe the reason is because trying to close the only window in the tab whilst the notification are still present causes this error. Looking at the PR to fix this, the notifications are now only being close *after* the window is closed which is too late/still triggers this error. I think they should be closed before the window is closed.

Alternatively I've tested using `tabclose` to close the neogit tab and that doesn't throw any error, so I'm guessing neogit is attempting to close the window not the tab.

N.B. I had thought this might relate to the notify plugin but I think it just reveals this issue because it's notifications are on a time delay whereas neogit's are immediate so they go away straight away

**Comment by mystilleef** [comment]
It's the same issue. I had to switch from `nvim-notify` to using the native `neogit` notification.

**Comment by TimUntersberger** [comment]
The easiest fix would be to just use the provided close binding `q` instead of whatever builtin vim operation.

> Alternatively I've tested using tabclose to close the neogit tab and that doesn't throw any error, so I'm guessing neogit is attempting to close the window not the tab.

I'll change to tabclose 👍

**Comment by TimUntersberger** [comment]
Using `tabclose` makes it possible to just leave the notifications open until they close on their own 👍

**Comment by akinsho** [comment]
Awesome 👍🏿 that resolves things on my end it seems 🚀 . Just wondering though is this change specific to the `tab` layout or will this break for split users? also regarding 

> The easiest fix would be to just use the provided close binding q instead of whatever builtin vim operation.

Not sure what you meant exactly but just wanted to clarify that I wasn't actually using a special binding just the default neogit q mapping although maybe you mean something else

**Comment by TimUntersberger** [comment]
> Just wondering though is this change specific to the tab layout or will this break for split users? also regarding

I always forget about 🤦. Thank you!

**Comment by mystilleef** [comment]
Didn't even know you could use `q` to close the main window. I only use for the commit window. Good to know.

**Comment by akinsho** [comment]
Think maybe this can be closed?

**Comment by mystilleef** [comment]
A quick test indicates this is no longer a problem. I'm closing.
