### ISSUE TITLE
Git error (128) !

### ISSUE THREAD

**Issue by teto** [TimUntersberger/neogit#36]
I keep seeing 
```
Git error (128) !
Press $ to see the command history
```
as notifications.

Not only that but pressing `$` does nothing. 
Is there a way to suppress these notifications ?
Btw I like your notification system and you may be interested in https://github.com/neovim/neovim/pull/13843

**Comment by teto** [comment]
more worrying seems like neogit autoremoves some files, disabling neogit fixed it.

**Comment by TimUntersberger** [comment]
> Not only that but pressing $ does nothing

I should probably change the message if the status buffer is not open, because `$` is only mapped when inside the status window.

> more worrying seems like neogit autoremoves some files, disabling neogit fixed it.
@teto which files were removed?

**Comment by teto** [comment]
It's a file I had just renamed. Everytime I opened it with neovim it would get emptied with neogit.

**Comment by TimUntersberger** [comment]
Could you please tell me the steps you took to encounter this issue?

**Comment by RianFuro** [comment]
@TimUntersberger  The errors should come from the renamed file. If git detects a rename, the output looks as follows:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    a.txt -> b.txt
```

We then naively put that into git commands:
```
 128 git diff a.txt -> b.txt
 128 git diff --cached a.txt -> b.txt
```

I can also reproduce that file getting emptied, most likely due to those diff commands. They'd be interpreted as piping the output from the diff commands to `b.txt` - which is nothing since the commands fail and their only output is on `stderr`
