### ISSUE TITLE
neogit spams all number registers on commit

### ISSUE THREAD

**Issue by tobealive** [TimUntersberger/neogit#401]
### Description

https://github.com/TimUntersberger/neogit/blob/5ad9c5d4baca3a9de9541409b3ed81b66c39c2b5/lua/neogit/buffers/commit_editor/init.lua#L52

When using this command to delete the commented out lines, they are deleted line by line in the vims number registers and therefore replace the current registers contents.

There doesn't seem to be need for this command after all, since commit messages are sent correctly without it. But maybe I don't see the point of having it.

Edit: the use of the term spam is perhaps a bit drastic, considering how deletion works in Vim, let's say it fills them.

**Comment by ten3roberts** [comment]
You are correct, this is no longer needed.

It persists from a time when a normal buffer was opened, and when written, was sent to git commit.

Now it uses the git-editor feature to make git open a file to write the commit message

**Comment by tobealive** [comment]
This also seems to be fixes now. So can be closed from my side

If it does not interfere with our schedule (since this is not a trivial question), perhaps you can give a short description of the difference between `silent g/^#/d` and `silent v/^#/d` or refer to the docs where this is explained. I must admit that I do not know yet.

**Comment by ten3roberts** [comment]
It is partially fixed, or atleast it no longer spams the registers on commit, but still does so when cancelling the commit.

The `silent g/^#/d` removed all comments, before the file was saved, read, and used as a commit message.

The behavior changed to use the builtin `GIT_EDITOR` where instead of `neogit` controlling the commit, `git` controls the commit and opens an instance of nvim. (which is now why the commit message is `.git/COMMIT_EDITMSG`, similar to if you just wrote `git commit` and made your editor of choice open.

Since git will commit with the file after the editor closes, the commit confirmation broke since git unconditionally sent the commit with the saved file.

`silent v/^#/d` deletes all lines which aren't a comment, essentially removing the commit message, which cancels the commit.

`:v` is the same as `:g!`, which means do the action for all lines `NOT` matched.

I've been told the mnemonic `global/regex/do` and `very not/regex/do`

See `:h global`
