### ISSUE TITLE
Way to save switches

### ISSUE THREAD

**Issue by otavioschwanck** [TimUntersberger/neogit#444]
Would be nice to have an key to remember the switches for some action (magit has)

**Comment by ten3roberts** [comment]
I agree, I frequently have to toggle `rebase local commits` and alike.

What would be your preferred way of saving them, should they persist between restarts?

**Comment by gegoune** [comment]
Could they not be read from git itself? This way Neogit's and cli git's behaviours will match and users will be able to set different options per repository if they wish so.

**Comment by CKolkey** [comment]
Could be as simple as writing a JSON file to `vim.fn.stdpath("state") .. "/neogit/state.json"` then serialize/deserialize it with `vim.json.{encode,decode}`. Then you just update the boolean keys in the change event when the user toggles it.

To have it be "per-project" instead of global (though I'm not sure thats better), we could use an approach similar to some session-manager plugins, where `vim.fn.stdpath("state") .. "/neogit/"` gets populated with files that are an encoded version of the CWD path for that session. So it could look like:

`vim.fn.stdpath("state") .. "/neogit/%%Users%%home%%code%%project.json"` (or similar)

Anyways, if that seems alright, I don't mind taking a swing at it.

**Comment by ten3roberts** [comment]
I've used that solution in the past.

The question is if there is any existing solution as to not reinvent the wheel or clutter the `state` directory

https://www.reddit.com/r/neovim/comments/10sso55/does_neovim_have_a_builtin_way_for_plugins_to/.

I'd be more than happy if you'd take a swing at it :smile:

**Comment by CKolkey** [comment]
Cool, here's a proof-of-concept. Seems to be working fine, though we can fine-tune the behaviour.
