### ISSUE TITLE
async from plenary

### ISSUE THREAD

**Issue by RianFuro** [TimUntersberger/neogit#51]
There's an open pull request at  nvim-lua/plenary.nvim#83 that takes the same approach we did with async (with inspriation from us apparently :grin:), makes it actually good (they already fixed a few performance concerns I had with my implementation) and adds it to plenary.
Now, I have no idea how widespread plenary actually is, so I have this question to @TimUntersberger and anyone who uses neogit and sees this: If this will be merged, should we *actually* depend on plenary (and not just for tests) and use their async library?

This would mean users would need to add plenary to their list of plugins if they'd want to use neogit.

**Comment by mjlbach** [comment]
I think depending on plenary is good, as much of plenary will likely make it into core at some point, and the async PR has a high likelihood of being merged.

**Comment by TimUntersberger** [comment]
I also feel like depending on plenary is a none issue, since a lot of plugins are already using the "library". Like @mjlbach said, I also think that most of the plenary stuff will make it into core (mostly because tj is the owner of the library).

Changing from our own solution to the async lib from plenary is probably a good idea 👍

**Comment by clason** [comment]
And maybe in return you could consider contributing your notification library to plenary? It's really quite lovely, and I'd love to use it as a `vim.notify` provider...

(Apropos: Not worth its own issue, but it'd look nicer if the notification highlight groups were linked to standard highlight groups -- like `MoreMsg`, `WarnMsg`, and `ErrMsg` -- rather than specific colors. I haven't tested it but from the code it looks like these are set unconditionally, so they would override the ones from a user's `init.vim` or color scheme should they set them there?)

**Comment by TimUntersberger** [comment]
> And maybe in return you could consider contributing your notification library to plenary? It's really quite lovely, and I'd love to use it as a vim.notify provider...

I don't think there is any point, because the library is already part of [neovim ui](https://github.com/mjlbach/neovim-ui)

**Comment by oberblastmeister** [comment]
I am also working on async await jobs as a follow up pr.

**Comment by oberblastmeister** [comment]
`async` `await` jobs are here! [link](https://github.com/nvim-lua/plenary.nvim/pull/101)

**Comment by oberblastmeister** [comment]
async await was merged!

**Comment by RianFuro** [comment]
@oberblastmeister thanks for all the work you put into it, looks amazing!
