### ISSUE TITLE
Fold colors suddenly change to difficult to read colors while scrolling buffer

### ISSUE THREAD

**Issue by mfiano** [TimUntersberger/neogit#61]
When I scroll the status buffer with an expanded unstaged/staged file, I see nicely colored changes with a red/green highlight. However, suddenly as I scroll, the red/green turn into a gray color, that is very difficult to read, and the only way to get it back to the nice colors seems to be to scroll far enough so the colored region is more than half way off screen, and then click somewhere outside of that region. Example:

Good: ![](https://i.lisp.cl/NbfaFg.png)

Scrolling down with mouse wheel, and at some point it looks like this:
![](https://i.lisp.cl/mwN3wH.png)

**Comment by RianFuro** [comment]
Huh, that would be the semantic highlighting not working well with your color scheme. It changes not because of the scrolling but your cursor moving into that region.
Basically, we have our own set of highlights for that since there's not really an equivalent in the defaults, so we just chose a set of greyscales.
You can check the readme on how to adapt those to your color scheme.

That being said, we probably should adapt the default highlighting to include fg colors, so it's at least readable.

**Comment by TimUntersberger** [comment]
@RianFuro it looks like the diff lines also have their color changed. I don't think this happens on my machine if I remember correctly.

**Comment by RianFuro** [comment]
@TimUntersberger We style the background since the expect the foreground to be highlighted red/green. With onedark the foreground is dark while the background is highlighted red/green. That's why the it looks off in his style, while it doesn't for me and you.

**Comment by RianFuro** [comment]
Alright, so I added some foreground colors to the highlights to make sure they are legible, no matter the user's colorscheme. I think that's as far as we can go on that matter, since we cannot possibly accommodate for all possible colorschemes out there; adaptions for that would need to go into the respective colorscheme plugin (even though I think we're not big enough to warrant that yet).

**Comment by Shatur95** [comment]
@RianFuro, is there a way to disable this feature? It looks weird with my colorscheme too:
Without highlighting:
![image](https://user-images.githubusercontent.com/22453358/112701645-df27cc80-8e99-11eb-8cc5-478fca64bc2f.png)
With highlighting:
![image](https://user-images.githubusercontent.com/22453358/112701665-f070d900-8e99-11eb-918f-3b1eab244921.png)

**Comment by RianFuro** [comment]
@Shatur95 There isn't as of right now, but we really should have that option so I'll add that in.
That being said, you can just check the `README.md` for which highlighting groups we are using and override those to match your colorscheme. In my experience the context highlight really helps when staging unstaging, as it shows you exactly what you're affecting.

**Comment by TimUntersberger** [comment]
@RianFuro Tbh I dislike the new change too. If possible we should probably keep the old behaviour and have a flag for foreground colors.

**Comment by RianFuro** [comment]
@TimUntersberger The problem is that we can't really do the right thing in this regard, someones color scheme will always look off with the provided colors.
I mean sure, we could add in a flag to only style the foreground too if set, but then do we also add a flag to invert diff highlighting to better match colorschemes like `onedark` and `nord`? What about light themes where the provided highlighting would likely be too dark? I wonder where we would draw the line between providing configuration via flags and just letting the user override the highlight groups.

On that note, maybe we should also add overrides for the most popular color schemes to our repo? Or at least accept pull requests for that so other users don't have to worry it.

**Comment by cloggier** [comment]
I don't think you should stress too much about what it looks like per colorscheme. There is absolutely no way you can support all colorschemes, as a matter of a fact it should be other way around - colorschemes should support your plugin and override default highlight groups it provides.

Come up with very neutral, non aggressive defaults and be done with it, I don't think any configuration flags should be provided here. If someone wants to disable specific highlighting they can do that by overriding it accordingly.

**Comment by RianFuro** [comment]
@Shatur95 just pushed an update, you can now set `disable_context_highlighting = true` in your setup call to completely disable context highlighting

**Comment by Shatur95** [comment]
@RianFuro, thank you!

**Comment by Shatur95** [comment]
@RianFuro, What if use `CursorLine` for it by default? Should looks awesome for any theme.
