### ISSUE TITLE
I don't quite understand the " neogit.status.create(<kind>)" command

### ISSUE THREAD

**Issue by hrqmonteiro** [TimUntersberger/neogit#62]
I guess i am not getting this straight. How can i configure Neogit to open in a split, or popup properly?

I created a config file, like `neogit.lua`, and put this on the file:

```
local neogit = require('neogit')

neogit.status.create('split')
```

But this way, everytime i open nvim, it automatically opens neogit in a split way, as soon as i open a file. And then if i close the buffer, and open  `:Neogit` again, it opens in the default tab way. So how do i properly configure this to everytime open in a split way?

**Comment by RianFuro** [comment]
The code above is not meant to configure neogit, it's actually spawning the window; that's why it opens the window as soon as you open a file.
You're meant to bind this to a mapping to command, I have this in my `init.vim` for example:
```viml
nnoremap <leader>gs <cmd>lua require'neogit.status'.create('split')<cr>
```
That translates to something like the following in lua i believe (I'm still doing basic configuration in viml, so I'm not entirely sure on that):
```lua
vim.fn.nvim_buf_set_keymap(0, 'n', '<leader>gs', "<cmd>lua require'neogit.status'.create('split')<cr>", { noremap = true });
```

You can also bind it to any command you like though. Neogit itself, for example, simply defines `:Neogit` like this:
```viml
command! -nargs=0 Neogit :lua require'neogit.status'.create()<CR>
```

**Comment by TimUntersberger** [comment]
@hrqmonteiro did the answer of @RianFuro satisfy you? Can I close this issue?

**Comment by hrqmonteiro** [comment]
Sure! Sorry i delayed so long. Thanks for the explanation @RianFuro
